/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import classes.pdv1;
import classes.pdv2;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import classes.produto;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ILSPereira-InfI171
 */
public class Caixa extends javax.swing.JFrame {

    int itens = 0;
    double VTG = 0;

    /**
     * Creates new form Caixa
     */
    public Caixa() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        qtdtxt1 = new javax.swing.JTextField();
        qtdtxt4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        qtdtxt = new javax.swing.JTextField();
        valortxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buttonmenos = new javax.swing.JButton();
        buttonmais = new javax.swing.JButton();
        qtdtxt3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        qtdtxt5 = new javax.swing.JTextField();
        jOptionPane1 = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        jLabel2.setText("Caixa - Vendas");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(220, 20, 200, 29);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 650, 60);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(null);
        jPanel3.add(qtdtxt1);
        qtdtxt1.setBounds(160, 30, 100, 30);
        jPanel3.add(qtdtxt4);
        qtdtxt4.setBounds(10, 30, 100, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(480, 20, 110, 40);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Finalizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(350, 20, 110, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setText("Troco");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(160, 0, 130, 29);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel10.setText("Valor Recebido");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(0, 0, 130, 29);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 430, 650, 70);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("valor unit");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(540, 280, 100, 29);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade", "Valor Unidade", "Valor Total"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 120, 430, 230);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setText("Lista de Itens");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 80, 200, 29);

        idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtActionPerformed(evt);
            }
        });
        idtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idtxtKeyPressed(evt);
            }
        });
        jPanel1.add(idtxt);
        idtxt.setBounds(440, 120, 150, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setText("Código");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 90, 110, 29);

        qtdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdtxtActionPerformed(evt);
            }
        });
        jPanel1.add(qtdtxt);
        qtdtxt.setBounds(440, 320, 80, 30);

        valortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valortxtActionPerformed(evt);
            }
        });
        jPanel1.add(valortxt);
        valortxt.setBounds(540, 320, 80, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setText("Total");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 360, 110, 29);

        buttonmenos.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        buttonmenos.setText("-");
        buttonmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmenosActionPerformed(evt);
            }
        });
        jPanel1.add(buttonmenos);
        buttonmenos.setBounds(540, 370, 70, 50);

        buttonmais.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        buttonmais.setText("+");
        buttonmais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmaisActionPerformed(evt);
            }
        });
        jPanel1.add(buttonmais);
        buttonmais.setBounds(450, 370, 70, 50);
        jPanel1.add(qtdtxt3);
        qtdtxt3.setBounds(160, 390, 100, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(440, 160, 110, 29);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setText("Qtde");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(440, 280, 70, 29);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel11.setText("QT itens");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 360, 110, 29);

        qtdtxt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdtxt5ActionPerformed(evt);
            }
        });
        jPanel1.add(qtdtxt5);
        qtdtxt5.setBounds(10, 390, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 650, 500);
        getContentPane().add(jOptionPane1);
        jOptionPane1.setBounds(170, 530, 262, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtActionPerformed

    }//GEN-LAST:event_idtxtActionPerformed

    private void valortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valortxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valortxtActionPerformed

    private void idtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idtxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ResultSet rs;
            produto p = new produto();
            rs = p.procurar(idtxt.getText());
            try {
                if (rs.next()) {
                    jLabel4.setText(rs.getString("codigo"));
                    valortxt.setText(rs.getString("Prvenda"));
                    jLabel7.setText(rs.getString("descriçao"));

                } else {
                    JOptionPane.showMessageDialog(null, "código não encontrado");
                    idtxt.setText("");

                }
            } catch (SQLException ex) {
                Logger.getLogger(Caixa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_idtxtKeyPressed
    private void novavenda(){
        idtxt.setText("");
        jLabel7.setText("");
        qtdtxt.setText("");
        valortxt.setText("");
        qtdtxt5.setText("");
        qtdtxt3.setText("");
        qtdtxt4.setText("");
        qtdtxt1.setText("");
        jLabel4.setText("");
      DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
      modelo.setRowCount(0);
      jTable1.setModel(modelo);
     jTable1.setRowSelectionInterval(0, 0);
}
    //botao+
    private void buttonmaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmaisActionPerformed
        double valor1, valor2;
        valor1 = Double.valueOf(qtdtxt.getText());
        valor2 = Double.valueOf(valortxt.getText());
        double total = valor1 * valor2;

        qtdtxt3.setText(String.valueOf(total));

        DefaultTableModel grid = (DefaultTableModel) jTable1.getModel();
        String[] dados = new String[4];

        dados[0] = (jLabel7.getText());
        dados[1] = (qtdtxt.getText());
        dados[2] = (valortxt.getText());
        dados[3] = (String.valueOf(total));
        grid.addRow(dados);
        itens = itens + 1;
        VTG = VTG + total;

        jTable1.setModel(grid);
        jTable1.setRowSelectionInterval(0, 0);

   // pdv2 oi = new pdv2();
        //oi.adicionar();

    }//GEN-LAST:event_buttonmaisActionPerformed

    private void qtdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtdtxtActionPerformed

    private void qtdtxt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdtxt5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_qtdtxt5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //jButton1.setText("Gravar");
        double valortotal;
        SimpleDateFormat formatoData = new SimpleDateFormat("YYYY/MM/dd");
        String data = formatoData.format(new Date());
        valortotal = Double.valueOf(qtdtxt3.getText());
        pdv1 pdv1 = new pdv1(0, data, valortotal);
        int numpdv1 = pdv1.incluir();

        for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
            //int idpdv2, int idpdv1, String produto, int qtdc, float valorunidade, float valor)
            String produto;
            float total;
            int qtd;
            float valorunitario;

            produto = jTable1.getValueAt(linha, 0).toString();
            qtd = Integer.valueOf(jTable1.getValueAt(linha, 1).toString());
            valorunitario = Float.valueOf(jTable1.getValueAt(linha, 2).toString());
            total = Float.valueOf(jTable1.getValueAt(linha, 3).toString());

            pdv2 oi = new pdv2(0, numpdv1, produto, qtd, valorunitario, total);
            if (oi.adicionar()) {
               
            }
        }
         JOptionPane.showMessageDialog(null, "Registro incluido com sucesso!");
 novavenda();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmenosActionPerformed
        int linhaSelecionada = -1;
        linhaSelecionada = jTable1.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        try {
            modelo.removeRow(linhaSelecionada);
            
        } catch (Exception e){
            jTable1.revalidate();
            jTable1.requestFocus();
            jTable1.setRowSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_buttonmenosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonmais;
    private javax.swing.JButton buttonmenos;
    private javax.swing.JTextField idtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField qtdtxt;
    private javax.swing.JTextField qtdtxt1;
    private javax.swing.JTextField qtdtxt3;
    private javax.swing.JTextField qtdtxt4;
    private javax.swing.JTextField qtdtxt5;
    private javax.swing.JTextField valortxt;
    // End of variables declaration//GEN-END:variables
}
